### ISSUE TITLE
Rework issue form to create a thread in same submission

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#660] opened 2016-11-18 21:08 UTC
Nikolai and I discussed earlier in the year a reworking of the issue page which essentially splits the issue part ('describe the problem') with the thread part ('let's discuss and take action'), so that essentially the form creates both at the same time.

Essentially this will at last hide the architectural database split between an issue and its container threads, rather than it being a glaring friction forced on the UI.

Additional thread creation against an issue can remain as present - the one-to-many relationship is correct.

**Comment by jf1** [comment] 2016-11-24 16:13
> essentially the form creates both at the same time.

I hope this will be driven by two separate input boxes in the same form, rather than have one lot of text repeated in the issue and the first post in the thread.

**Comment by mvl22** [comment] 2016-11-24 17:55
> I hope this will be driven by two separate input boxes in the same form

Yes.

**Comment by mvl22** [comment] 2018-07-23 16:14
This will also reduce the number of e-mails in total from 2 to 1.

**Comment by nikolai-b** [comment] 2018-11-18 19:32
@mvl22 I think this is a deign problem (i.e. something that I can't pick up yet)?  Is that correct?

**Comment by mvl22** [comment] 2018-11-18 20:53
> I think this is a design problem (i.e. something that I can't pick up yet)? Is that correct?

No, I think it's just a case of merging the two forms, in terms of the UI, isn't it?

**Comment by nikolai-b** [comment] 2018-11-20 22:19
Great, I misunderstood this issue then.  Is this just a case of adding the new thread fields to the issue form:

![new thread](https://user-images.githubusercontent.com/6289830/48806321-de069380-ed11-11e8-885a-4c0b1e44c8f2.png)

What should we call these to make it clear it is separate?

I could just have a spacer and exactly what is there currently, i.e.

Thread:

This is where a discussion about the issue is started.
There could be many different discussion threads that one issue creates
e.g. a new planning application may affect traffic on a road and affect cycle access to woods.

Thread Title:

Thread Owned by:

Thread description:

**Comment by mvl22** [comment] 2018-11-21 01:16
Yes, it should just be adding that field.

I suggest labelling like:

- What is the issue?
- Start a conversion on this, describing your thoughts on what should be done:

I'm sure this could be better though!

**Comment by nikolai-b** [comment] 2019-01-13 21:46
@mvl22 I'm not sure where you wanted the text you suggested to be added.  I've come up with this:
 
![screenshot from 2019-01-13 21-37-37](https://user-images.githubusercontent.com/6289830/51090947-96cdd980-177b-11e9-8f9b-f7e4c925c3e0.png)

Please let me know if that is what you wanted.  It does make the new issue form rather long.  It brakes the tests so I'll fix them and push to staging soon.

**Comment by mvl22** [comment] 2019-01-14 00:56
Can you show the full form - I can only see the bottom half.

If using Firefox, you can get it to take a full page 'screenshot':
https://support.mozilla.org/en-US/kb/firefox-screenshots

**Comment by mvl22** [comment] 2019-01-18 15:09
Is it possible to get this into Staging? I can then see the form and can perhaps come back with a modified prototype in the form of a modified HTML page.

**Comment by nikolai-b** [comment] 2019-01-20 20:42
@mvl22 it should be in staging soon, once the cron job has run.

**Comment by nikolai-b** [comment] 2019-02-26 20:44
@mvl22 if your happy with this in staging then can it be merged into master?  There are a few other fixes that it is holding up.

**Comment by mvl22** [comment] 2019-03-18 23:19
Thanks; this is a huge improvement. I like that it takes people directly to the thread within the issue.

Problems:

- In section 5, can you change "Write a description" to "Describe the problem".

- Image is giving "translation missing: en.photo.wrong_format" when I select a PNG file. This seems to be a regression.

- If the thread title section (second part, field 1) is empty, can you set this to live-mirror whatever is typed into the issue title (first part, field 1)? In most cases, people will want these to be the same, and it makes sense for the first thread to have the same title in most cases. We should still allow people to change it, but by the time they have scrolled down this far, it makes sense for it to be pre-filled.

- I've added a separate ticket #843 about the textarea. (This is not a regression, so don't let this hold things up, but do fix if it's quick to do at the same time as the other changes)

- The all day button is visually stretched in Chrome/Mac. (Again, not a regression, so not a blocker.)

**Comment by nikolai-b** [comment] 2019-03-22 06:30
> If the thread title section (second part, field 1) is empty, can you set this to live-mirror whatever is typed into the issue title (first part, field 1)? In most cases, people will want these to be the same, and it makes sense for the first thread to have the same title in most cases. We should still allow people to change it, but by the time they have scrolled down this far, it makes sense for it to be pre-filled.

Because we've made this HTML this is a little complicated (but not very), also I assume we'd want to stop pre-filling if the user made any changes in 2nd input.  Given we had feedback that is was annoying that it was pre-filled then I'd prefer if now they are on the same form we left it to users.

**Comment by nikolai-b** [comment] 2019-03-22 07:24
Sorry, shouldn't have closed in that commit.  I should have just referenced this issue and then asked if it was ok to not update the second part field 1.

**Comment by mvl22** [comment] 2019-03-22 15:37
> Because we've made this HTML this is a little complicated (but not very), also I assume we'd want to stop pre-filling if the user made any changes in 2nd input.

Yes: "If the thread title section (second part, field 1) is empty ..."

> Given we had feedback that is was annoying that it was pre-filled then I'd prefer if now they are on the same form we left it to users.

I don't remember that feedback, but we are already doing this anyway in the two-stage version. I think it will be far more annoying to users to have to invent a second title when the first will be right in 99% of cases.

**Comment by nikolai-b** [comment] 2019-03-22 15:51
https://github.com/cyclestreets/cyclescape/commit/cd3f4a95fcdda98dd380141e2ce3f85cd972cdfe#r10009305

I remember another user saying it was very confusing.  If it is a blocker I'll implement it tomorrow but just wanted to check.

**Comment by mvl22** [comment] 2019-03-22 15:59
> cd3f4a9#r10009305

That is referring to the description block (not the title) appearing twice, i.e. that the first message repeats the description, but that's not going to happen now anyway as they'll be putting in other text.

I do think it's important this is done and should be regarded as a blocker - it means that we'll end up with unnecessarily inconsistent titles created and random stuff put in by users by way of frustration with having to put a second title that mostly will be the same.

**Closed** 2019-03-23 09:22 UTC

**Comment by mvl22** [comment] 2019-03-23 11:58
Thanks for fixing those up.

All good to go now!
