### ISSUE TITLE
Auto linkification of threads

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#428] opened 2015-10-23 20:59 UTC
Suggestion from @si-the-pie:

Would be nice: Auto linkification

That could handle cases like: 
thread 1051 
thread no 1051 
thread number 1051

Or more geeky variants such as:

t1051 
#t1051

Check how users are referring to threads.

#hashtag which would link to the tag page for that same string, e.g. #cycleparking would be hyperlinked to /tags/cycleparking

**Comment by rbazinet** [comment] 2016-01-06 16:25
@mvl22 where do you see this feature used? I'm new to the system so a bit of guidance would be appreciated. I see new threads may reference other threads as one location. Where else?

**Comment by mvl22** [comment] 2016-01-06 16:57
This would ideally apply wherever user-generated text is present.

For now, I suggest just enabling it in the main text area in a message thread, and we can roll it out further from then on.

If you go to the front page of the site: http://www.cyclescape.org/ , sign in in the top-right, then click on any discussion thread, e.g. "Westminster's proposals for Green Park to Marylebone Quietway", it would be in the message box at the bottom where the message is typed.

Thread 80 (and variants suggested above) would link to ```/threads/80```
"Issue 86" (and similar variants like "issue no. 80") would link to ```/issues/86-cambridge-science-park-station```

**Comment by mvl22** [comment] 2016-01-06 16:59
I think the variants we should permit are:

thread 1051 
thread no 1051 
thread no. 1051 
thread number 1051
thread #1051
#t1051

and then the same for issue, replacing "thread" with "issue" in the list above.

I suggest doing this as a list that can easily be expanded in the future as we see how users use it.

**Comment by mvl22** [comment] 2016-01-06 17:06
I've edited the above reply to make clear that this obviously something that will only end up visible to the user once the text is saved, i.e. it's a view context thing.

(Naturally, text should be scanned at view time, definitely not saved hard-coded that way in the database.)

**Comment by rbazinet** [comment] 2016-01-07 22:20
@mvl22 this is a fun one to work on. I have this working for threads and issues. I need to work on some tests actually...do you want to try it out before I get the tests done or wait until it's all complete?

**Comment by mvl22** [comment] 2016-01-07 22:54
I'm not going to be able to try it tonight (it's 11pm) here, so I just ploughing on with the tests!

**Comment by mvl22** [comment] 2016-01-07 23:04
Just to say that there's a What's New listing, linked from the bottom of the page - ideally items should be added to that as they are finalised.

**Comment by rbazinet** [comment] 2016-01-08 21:48
@mvl22 I am having some issues with testing. There is only one single view test for the application so I'm missing some conventions in this app.  I'd suggest taking the commit feature branch and ask @nikolai-b to take a look at why my test will not pass. It makes me wonder why there are only one other view test too.  Maybe not needed? This feature needs a view test because we need the rendered page to test, not pre-rendered data. I hope this make sense.  

I spent some time today on this but don't want to burn up our time with something @nikolai-b may know right off.

**Comment by nikolai-b** [comment] 2016-01-09 09:38
I added a view test hoping to speed up the tests but it was a bit cheeky as @mvl22 hasn't prioritised this.  

We [render views](https://github.com/cyclestreets/cyclescape/blob/master/spec/spec_helper.rb#L34) in the controller specs and the convention has been to test the view from there.  Feel free use view specs if you prefer or stick with the more roundabout controller specs.  I found setting up the view spec harder than the controller spec and not much faster.

**Comment by rbazinet** [comment] 2016-01-09 15:57
Yes, that's exactly the issue I found. I'll look at how you've been implementing the view tests via the controllers. I definitely found some difficulties in the view tests I attempted. Glad you replied and confirmed. Thanks.

**Comment by rbazinet** [comment] 2016-01-14 15:54
@mvl22 this has been committed in branch issue-428 but it really needs view tests. It would be good to have some help from @nikolai-b if possible.

**Comment by mvl22** [comment] 2016-01-23 20:56
@nikolai-b Assuming you're happy, please do merge.

https://github.com/cyclestreets/cyclescape/commits/issue-428

There's an unimplemented test (as noted above) but the code can go live and we can sort the test out later.

**Comment by nikolai-b** [comment] 2016-03-19 12:12
Closed in #499

**Closed by nikolai-b** 2016-03-19 12:12 UTC
