### ISSUE TITLE
Change locale according to user browser, allow to switch language

### ISSUE THREAD

**Issue by PetrDlouhy** [cyclestreets/cyclescape#489] opened 2016-01-11 09:39 UTC
Right now, the site is shown only in one language, that is set in config. For user comfort, it should be displayed in his language determined by browser identification. It would be good to add language switcher, so user can change the language if he is not satisfied by automatic choice.

This would require, that all `Cyclescape` instances in locale are replaced by configurable site name as mentioned in #433. So on our site the name `Cyklisté sobě` is displayed in all language versions and on original site is `Cyclescape` everywhere.

**Comment by PetrDlouhy** [comment] 2016-01-11 09:40
The language switcher would be also quite useful in translation/translation revision process.

**Comment by mvl22** [comment] 2016-01-11 11:12
Duplicate of #277. Pull requests also welcome, as ever.

**Closed by mvl22** 2016-01-11 11:12 UTC

**Comment by PetrDlouhy** [comment] 2016-01-11 11:57
Sorry for the dupe, I tried to find `locale`, but not `translation`.

I would like to make more contribution, but I am programming mostly in Django/Python and I am occupied with our other projects. So every change takes me much more time as I don't know much about RoR.

We are trying to find a Ruby programmer for this, we even have some funding (private donation) for him. So far we were unsuccessful in the search, but we will keep on searching.

**Comment by mvl22** [comment] 2016-01-11 21:31
> Sorry for the dupe, I tried to find locale, but not translation.

Good point - yes, that is a more obvious term to be searching on! I've updated the issue concerned.

> We are trying to find a Ruby programmer for this, we even have some funding (private donation) for
> them. So far we were unsuccessful in the search, but we will keep on searching.

I've dropped you an e-mail about this.
