### ISSUE TITLE
Redirect loop 

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#416] opened 2015-10-07 22:53 UTC
http://www.cyclescape.org/settings/edit

as linked from
http://www.cyclescape.org/settings/profile

is giving a redirect loop.

**Comment by mvl22** [comment] 2015-10-08 09:01
This is now causing the buttons linked on
https://www.cyclescape.org/settings/edit
to behave like this problem:
https://github.com/cyclestreets/cyclescape/issues/403#issuecomment-146357767

i.e. they no longer result in navigation, and a mixed content over AJAX warning appears in the console.

**Comment by nikolai-b** [comment] 2015-10-08 18:27
Is there any reason we can't make the whole site ssl?  I think the problem is the switching between protocols.

**Comment by mvl22** [comment] 2015-10-08 19:44
I suppose we could do - but this was working before so what has changed?

**Comment by nikolai-b** [comment] 2015-10-08 19:52
In the upgrade of devise or rails this page stopped being https, I'm not sure why, do you want me to investigate?

If your happy I can use a `force_ssl = true` config option and make that the default.

**Comment by mvl22** [comment] 2015-10-08 20:13
I'd prefer we restore the previous behaviour before considering just bugging the whole site in HTTPS because that hasn't been properly considered, when this really feels like a regression.

What should be in place is that any page relating to account security should be HTTPS - can you double-check that is all being done.

I presume there is now an AJAX-based page replace mechanism in place which is accounting for the console messages. Those presumably are cases where the user is on an HTTP page but it tries to load an HTTPS page.

I guess all the /settings hierarchy needs to be HTTPS and that will then put everything in sync.

**Comment by nikolai-b** [comment] 2015-10-10 11:18
So https://github.com/cyclestreets/cyclescape/commit/6ee3314c003adec4321680793d816d7500ea9fb6 should fix the mixed content message, it will do a full page reload but I can't really see how to stop that without making the location and preferences controllers use SSL which seems arbitrary, they are no more sensitive than other pages.  I'm still not sure what caused this change, either devise, rails or jQuery tools.  If your happy with this can you close the issue?

**Comment by mvl22** [comment] 2015-10-10 17:37
Rolled out, and it is less bad, but still producing ajax/history errors in the console - please log into the site and see yourself (open the console, leave it open, navigate from the front page to the user pages, and navigate around that area, and you'll see errors appearing). Are you able to produce this on your browser in live, and on your dev machine?

I strongly suspect the addition of the AJAX-based page component replacement stuff in turbolinks:
https://github.com/rails/turbolinks

I'm not really keen on that kind technique, whereby page components are replaced in the current page and the URL is manipulated: it's like trying to rework HTTP.

I've never been clear why jquery loading actually needed turbolinks?
https://github.com/cyclestreets/cyclescape/commit/041e5841f01a5e82b3563f4da6e4830b5dd683c5

**Comment by nikolai-b** [comment] 2015-11-03 10:56
Removed turbolinks in https://github.com/cyclestreets/cyclescape/commit/f619864daa5ce225c6c3c937e1e556aa361e82b4

**Closed by nikolai-b** 2015-11-03 10:56 UTC
