### ISSUE TITLE
New thread form is still too large for browser window and provides no option/ability to scroll. (only works with down arrow). Submit thread button cannor be seen

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#515] opened 2016-02-22 12:47 UTC
This simple issue really would be a barrier to new people using Cyclescape and must be resolved.

**Comment by mvl22** [comment] 2016-02-22 13:29
Duplicate of #445.

**Closed by mvl22** 2016-02-22 13:29 UTC
