### ISSUE TITLE
Getting 500 response when updating subscription preferences

### ISSUE THREAD

**Issue by sam-7** [cyclestreets/cyclescape#427] opened 2015-10-21 14:06 UTC
Request URL:http://www.cyclescape.org/users/***snip***/prefs
Request Method:POST
Status Code:500 Internal Server Error

I'd be happy to look into this further but I think it needs access to the server log

**Comment by smsm1** [comment] 2015-10-21 14:15
I would be useful to know which what change to the user preferences you were making, to narrow down the cause.

**Comment by sam-7** [comment] 2015-10-21 14:44
Was trying to change 'Matters near my location' from 'Notify me of new issues and automatically follow all new threads' to 'Notify me of new issues and when new threads are started'

Form data (parsed):
utf8:✓
_method:patch
authenticity_token:***snip***
user_pref[involve_my_locations]:notify
user_pref[involve_my_groups]:notify
user_pref[involve_my_groups_admin]:0
user_pref[involve_my_groups_admin]:1
user_pref[enable_email]:0
user_pref[enable_email]:1
commit:Save


The keys with 0 and 1 entries look suspicious to me.

**Comment by sam-7** [comment] 2015-10-21 18:53
No, nothing to do with the 0,1 entries.  It fails when user_pref[involve_my_locations] is set to notify or none.  I suppose it might only be when trying to change the value of user_pref[involve_my_locations].  Subscribe is the default value for that column

**Comment by mvl22** [comment] 2015-10-21 22:15
@sam-7 This is now rolled out on the live site - could you try again now?

Thanks very much for reporting this.

(PS If you've any Rails experience, and would like to get involved, pull requests are very welcome! We're happy to spend time helping people getting set up, naturally.)

**Comment by sam-7** [comment] 2015-10-21 22:35
Thanks, I can now save my preferences.  Is unsubscribing from all threads really the behaviour you want here?  My expectation, as a user, would be that existing subscriptions remained unchanged and only new threads would be affected.

**Comment by mvl22** [comment] 2015-10-21 22:41
@sam-7 @nikolai-b Yes, I agree, this should not affect existing subscriptions; Nikolai, can you check?

**Comment by nikolai-b** [comment] 2015-10-22 07:22
@mvl22 
https://github.com/cyclestreets/cyclescape/blob/master/spec/models/user_pref_observer_spec.rb#L239
Looking at the specs it does seem like it is what it did do (although I may have been a bit overzelous in what it now unsubscribes you from).  Should I remove all the unsubscribe parts as I fully agree they don't make sense?

**Comment by sam-7** [comment] 2015-10-22 20:55
Sounds good to me.  Thanks.  Do you think subscribe is the right default for new users?  It generates a lot of email if you have email notifications enabled.

I'd love to learn Rails but just don't have the time at the moment.  Sorry.

**Comment by mvl22** [comment] 2015-10-22 22:52
> Do you think subscribe is the right default for new users?

Would you mind asking that same question at #198, where there is a discussion on exactly that question.

> I'd love to learn Rails but just don't have the time at the moment. Sorry.

No problem! If you'd be interested in helping with other things, like helping refine bug reports, or working out the changes to the CSS we need to make the site mobile-friendly, let us know :) No pressure though - your report above was helpful!

**Comment by nikolai-b** [comment] 2015-10-25 12:50
Hi,
As this issue was about a 500 (and not about if we should change from unsubscribing existing threads to not subscribing on new threads) I'm closing it.

**Closed by nikolai-b** 2015-10-25 12:50 UTC
