### ISSUE TITLE
Issues nearby does not give location, map is blank.

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#513] opened 2016-02-22 12:37 UTC
When looking at "issues nearby" it doesn't take you to the area in question. 

Zooming results in a blank map. 

http://camcycle.cyclescape.org/issues#map-pane

**Comment by mvl22** [comment] 2016-02-22 13:33
> When looking at "issues nearby" it doesn't take you to the area in question.

Duplicate of #464

> Zooming results in a blank map.

Duplicate of #468

**Closed by mvl22** 2016-02-22 13:33 UTC
