### ISSUE TITLE
Cannot create thread for issue created from Planning Appplication

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#402] opened 2015-08-03 09:47 UTC
Occurs when a new issue has been created from a planning application. When clicking on "discuss" to create a thread the pop up box is too large so the details cannot be entered and the submit button cannot be clicked.

**Comment by roxannedebeaux** [comment] 2015-08-03 09:48
This can be worked around by going back to the list of issues and clicking from there.

**Comment by smsm1** [comment] 2015-08-03 09:56
I think this will be the same as #400

**Comment by mvl22** [comment] 2015-08-03 11:25
Duplicate of #400.

**Closed by mvl22** 2015-08-03 11:25 UTC
