### ISSUE TITLE
Jump to top 

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#447] opened 2015-11-11 14:13 UTC
When I use cyclescape on a mobile device it is very difficult to get back to the top of the page. The pages are too long for scrolling back to the top. A "jump to top" link would be hugely helpful for navigating on a mobile device (which I do regularly).

**Comment by mvl22** [comment] 2015-11-11 14:21
Partial duplicate of the broader issue #222, a general policy issue which remains to be resolved but is definitely moving up the list.

Though for now a workaround could be put in, to add a link as suggested.

(NB: On an iPhone, there is a standard 'scroll to top' method which works on virtually any app, which is to click on the very top bar at the start of the whole screen area.)

**Closed** 2015-11-22 21:11 UTC
