### ISSUE TITLE
Missing query parameter: 56 issues found for '':

### ISSUE THREAD

**Issue by PetrDlouhy** [cyclestreets/cyclescape#481] opened 2016-01-10 15:02 UTC
On the tag summary page, e.g. `http://www.cyclescape.org/tags/consultation` is missing the name of the tag in the string `56 issues found for '':`.

**Comment by mvl22** [comment] 2016-01-10 18:09
Duplicate of #463.

**Closed by mvl22** 2016-01-10 18:09 UTC
