### ISSUE TITLE
Give issues or threads an email address

### ISSUE THREAD

**Issue by iainlane** [cyclestreets/cyclescape#380] opened 2015-06-11 20:44 UTC
A proposed workflow for dealing with an issue could be this.
1. Create it on Cyclescape
2. Create a thread
3. Retrieve an email address for this thread and switch to regular email for corresponding with others (e.g. local authority officers) who aren't on cyclescape, keeping this email in CC or BCC

also it would be great to be able to forward (or bounce if your client offers this) emails to the thread if it isn't kept in CC for whatever reason.

**Comment by iainlane** [comment] 2015-06-17 10:02
I see that threads do already have an email address (thread-hash@cyclescape.org), so perhaps this issue is asking for the following

  1. Allow, possibly by a per-thread setting (if this isn't on then drop mails into moderation), emails from non group and non cyclescape members through to threads on cyclescape.
  2. Show a thread's email address somewhere on its page on the web UI

**Comment by mvl22** [comment] 2015-06-17 10:24
Partial duplicate of #44.

**Comment by mvl22** [comment] 2016-11-18 20:59
Threads do indeed now have a "Or reply by email" link at the end of the page, which gives the e-mail address.

**Closed by mvl22** 2016-11-18 20:59 UTC
