### ISSUE TITLE
Planning application not appearing in Cyclescape search

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#620] opened 2016-08-15 13:32 UTC
16/1389/FUL

https://idox.cambridge.gov.uk/online-applications/applicationDetails.do?activeTab=documents&keyVal=OAWRENDXMUZ00

**Comment by roxannedebeaux** [comment] 2016-08-15 13:36
Last update appears to have been 4th August

**Comment by roxannedebeaux** [comment] 2016-08-22 10:32
This one is also not appearing: 16/1529/FUL
https://idox.cambridge.gov.uk/online-applications/applicationDetails.do?activeTab=documents&keyVal=OC29TXDXFIA00

**Comment by roxannedebeaux** [comment] 2016-08-22 10:33
Likewise: 16/1359/FUL

**Comment by roxannedebeaux** [comment] 2016-09-12 15:32
Another planning application not coming up in search: 16/1626/FUL

Lately there always seems to be at least one application not coming through. Do we know why?

https://idox.cambridge.gov.uk/online-applications/applicationDetails.do?activeTab=documents&keyVal=OD3DYSDXFTG00

**Comment by nikolai-b** [comment] 2016-11-08 20:29
Fixed in 22b6fff7686bc1

**Comment by mvl22** [comment] 2016-11-08 20:33
Can you clarify how that fix 22b6fff resolves the example problems above?

That commit only seems to add new areas (and add the rollbar fix). But examples are all from Cambridge, which was already in the list.

**Closed** 2016-11-09 08:05 UTC

**Comment by nikolai-b** [comment] 2016-11-09 08:08
That commit removes invalid region, it doesn't add any.
It also catches JSON errors instead of leaving them unhandled so a bad region doesn't cause the job to crash.

**Comment by mvl22** [comment] 2016-11-09 15:38
> It also catches JSON errors instead of leaving them unhandled so a bad region doesn't cause the job to crash.

Ah - great.

**Comment by roxannedebeaux** [comment] 2016-12-05 11:55
Another planning application not coming up in Cyclescape:
S/3064/16/OL

http://plan.scambs.gov.uk/swiftlg/apas/run/WPHAPPDETAIL.DisplayUrl?theApnID=S/3064/16/OL&theTabNo=3&backURL=%3Ca%20href=wphappcriteria.display%3ESearch%20Criteria%3C/a%3E%20%3E%20%3Ca%20href=%27wphappsearchres.displayResultsURL?ResultID=1552882%26StartIndex=1%26SortOrder=rgndat:desc%26DispResultsAs=wphappsresweek1%26BackURL=%3Ca%20href=wphappcriteria.display%3ESearch%20Criteria%3C/a%3E%27%3ESearch%20Results%3C/a%3E

**Comment by mvl22** [comment] 2016-12-05 13:52
> S/3064/16/OL

The problem is that the location of that planning application is just outside your area. Cyclescape shows planning applications that are within your defined area of interest - it has to, otherwise it would have know way of knowing that you don't want things in Edinburgh, or London, or whatever.

Extend your boundary a bit further to the West at:
https://camcycle.cyclescape.org/settings/locations
and it should then appear.
